name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Hello, world!"
      - name: Print Goodbye
        run: echo "Goodbye, world!"
      - name: Multi-line steps
        run: |
          echo "This is line 1"
          echo "This is line 2"
          echo "This is line 3"
